version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production # Явно указываем production stage
    container_name: node_app_prod
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PORT: ${APP_PORT}
      NODE_ENV: production
      DB_SSL: false
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres-net

  postgres:
    image: postgres:16.1-alpine
    container_name: postgres_db_prod
    environment:
      - PGPORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - postgres-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  postgres_data_prod:
    driver: local

networks:
  postgres-net:
    driver: bridge