version: '3.8'

services:
  app:
    build:
      context: .
      target: production # Явно указываем production stage
    container_name: node_app_prod
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME:-mydatabase_prod}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_SSL=false
    env_file:
      - .env
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    container_name: postgres_db_prod
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME:-mydatabase_prod}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data_prod:

networks:
  app-network:
    driver: bridge